server:
  port: 1114
spring:
  application:
    name: authentication
  datasource:
    url: jdbc:mysql://
    username: xxxxxx
    password: xxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: xxx.xxx.xxx.xxx
      port: 27017
      database: lfs
      uri: mongodb://
  redis:
    port: 6379
    host: xxx.xxx.xxx.xxx
    password: xxxxxx
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka


