server:
  port: 1200
spring:
  application:
    name: open-ai
  data:
    mongodb:
      host: xxx.xxx.xxx.xxx
      port: 27017
      database: lfs
  redis:
    port: 6379
    host: xxx.xxx.xxx.xxx
    password: xxxxxx
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka


openapi:
  key: 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
