server:
  port: 1200
spring:
  application:
    name: open-ai
  data:
    mongodb:
#      uri: mongodb://root:google123@120.24.95.4:27017/lfs?authSource=admin
      host: 120.24.95.4
      port: 27017
      database: lfs
  redis:
    port: 6379
    host: 120.24.95.4
    password: google123
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka


openapi:
  key: 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
