server:
  port: 1113
spring:
  application:
    name: system
  datasource:
    url: jdbc:mysql://120.24.95.4:3306/lfs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 6tfc^YHN
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://root:google123@120.24.95.4:27017/lfs?authSource=admin
      host: 120.24.95.4
      port: 27017
      database: lfs
  redis:
    port: 6379
    host: 120.24.95.4
    password: google123
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka


